modLoader="javafml"
loaderVersion="[41,)"
license="GPL3"

[[mods]]
modId="nzgexpansion"
version="1.3.2"
displayName="NineZero's Gun Expansion"
updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/ninezeros-gun-expansion"
logoFile="nzgexpansion_banner.png"
authors="zaeonNineZero"
description='''
An addon for MrCrayfish's Gun Mod, adding additional weapons and attachments in an aesthetically simple style.
'''

[[dependencies.nzgexpansion]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nzgexpansion]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nzgexpansion]]
    modId="framework"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.nzgexpansion]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.4,)"
    ordering="AFTER"
    side="BOTH"

[modproperties.nzgexpansion]
    catalogueImageIcon="nzgexpansion_icon.png"
